### ISSUE TITLE
Missing Requirements File

### ISSUE THREAD

**Issue by BurnsCommaLucas** [ohAnd/trmnlServer#1]
Heya, the readme indicates that a top level `requirements.txt` should exist but no such file is in the repo. Maybe just an oversight on first commit?

**Comment by ohAnd** [comment]
you're right ;-)

added this now - including last local changes

see [commit](https://github.com/ohAnd/trmnlServer/commit/60ecd32dedee9b1a5b00bf3e9f1b02b653c5c77e)
